title: Golang Project Template
remote-theme: just-the-docs/just-the-docs
logo: "https://common-go.carloslapao.com/images/logo.png"
search_enabled: true
aux_links:
  "On Github":
    - "https://github.com/cjlapao/go-template"
aux_links_new_tab: false
footer_content: "Copyright &copy; Carlos Lapao <a href=\"https://opensource.org/licenses/MIT\">MIT license.</a>"
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false